"""empty message

Revision ID: 5ce40b4e4427
Revises: 7bb3720c1969
Create Date: 2018-03-29 09:36:27.822218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce40b4e4427'
down_revision = '7bb3720c1969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('signature', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'signature')
    # ### end Alembic commands ###
